import './globals.css'

export const metadata = {
  title: 'testing-tailwindcss',
  description: 'Generated by Rabees Hussain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full bg-gradient-to-tr from-gray-400 to-gray-950 rounded-full lg:p-8 sm:p-0 md:p-8">{children}</body>
    </html>
  )
}
